const DATAS ={
    delivery: '1. Declaramos ainda, que é responsabilidade do usuário acima citado zelar pela guarda deste equipamento, e em casos de extravio, dano parcial ou total e avaria do equipamento entregue, o usuário deve comunicar imediatamente o departamento ICT e Segurança Cibernética.', 
    devolution: '',
    simCard: '1. O cartão é propriedade da CdM, e será atribuído ao trabalhador por um período mínimo de 1 anos renováveis (caso não haja alterações), devendo ser utilizado a serviço da empresa tendo em vista a atividade exercida pelo trabalhador, sendo terminantemente proibidos o empréstimo, aluguel ou cessão deste a terceiros. 2. O trabalhador deverá zelar pelo uso e conservação do cartão de forma correta, sendo que, durante o período de utilização, quaisquer trocas, perda, extravio do cartão ou reposições por causa não devidamente justificada, implica o ressarcimento junto a empresa, inerentes à substituição do cartão. Se a empresa ressarcir, o valor será debitado ao trabalhador. 3. No exercício das suas actividades, o trabalhador deve assegurar a sua disponibilidade sempre que solicitado, devendo em caso de perda do cartão, comunicar imediatamente a empresa. 4. É responsabilidade do trabalhador fazer uso do crédito atribuído pela empresa com diligências e responsabilidade, não devendo efetuar transferências do mesmo para outros números. Em caso de viagens para fora do País, aconselha-se a usar o Wi-Fi e a desativar os serviços de roaming. 5.Ao término da prestação de serviço ou do contrato individual de trabalho, o trabalhador compromete-se a devolver o cartão em perfeito estado, quando for comunicado o seu desligamento. ',
    cellphone: '1. O aparelho é propriedade da CdM, e será atribuído ao trabalhador por um período mínimo de 2 anos renováveis, devendo ser utilizado a serviço da empresa tendo em vista a atividade exercida pelo trabalhador, sendo terminantemente proibidos o empréstimo, aluguel ou cessão deste a terceiros. 2.	O trabalhador deverá zelar pelo uso e conservação do aparelho de forma correta, sendo que, durante o período de utilização, quaisquer trocas, perda, extravio do aparelho ou reposições por causa não devidamente justificada, implica o ressarcimento junto a empresa, inerentes à substituição do aparelho. Se a empresa ressarcir, o valor será debitado ao trabalhador. 3.	No exercício das suas actividades, o trabalhador deve assegurar a sua disponibilidade sempre que solicitado, devendo em caso de perda do aparelho, comunicar imediatamente a empresa. 4.	É responsabilidade do trabalhador fazer uso do crédito atribuído pela empresa com diligências e responsabilidade, não devendo efetuar transferências do mesmo para outros números. Em caso de viagens para fora do País, aconselha-se a usar o Wi-Fi e a desativar os serviços de roaming. 5.	Ao término da prestação o de serviço ou do contrato individual de trabalho, o trabalhador compromete-se a devolver o aparelho em perfeito estado, quando for comunicado o seu desligamento.',
    cellAndMobile: ''
}

export default DATAS
